project:
  type: website

website:
  title: "Metabolomics Data Analysis Course"
  sidebar:
    background: primary
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: sessions.qmd
        text: Sessions and Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

